#!/usr/bin/env bash

# Canonical settings for the plain ContextSniper search/edit baseline.
# Both the original Claude SWE runner and ContextSniper-Codex source this file.
# Keep host-, workspace-, port-, and session-specific values in each runner.

export CONTEXTSNIPER_CODE_TOGGLE_FORCE="${CONTEXTSNIPER_CODE_TOGGLE_FORCE:-true}"
export CONTEXTSNIPER_SEARCH_LIMIT="${CONTEXTSNIPER_SEARCH_LIMIT:-}"
export CONTEXTSNIPER_SEARCH_FORCE_LIMIT="${CONTEXTSNIPER_SEARCH_FORCE_LIMIT:-${CONTEXTSNIPER_SEARCH_LIMIT:-}}"
export VECTOR_DB_TYPE="${VECTOR_DB_TYPE:-memory}"
export CONTEXTSNIPER_CODE_TOGGLE="${CONTEXTSNIPER_CODE_TOGGLE_FORCE:-true}"

export EMBEDDING_PROVIDER="${EMBEDDING_PROVIDER:-openai}"
export CONTEXTSNIPER_EMBEDDING_MODEL="${CONTEXTSNIPER_EMBEDDING_MODEL:-openai/text-embedding-3-small}"
export CONTEXTSNIPER_EMBEDDING_BASE_URL="${CONTEXTSNIPER_EMBEDDING_BASE_URL:-https://openrouter.ai/api/v1}"
export CONTEXTSNIPER_EMBEDDING_API_KEY="${CONTEXTSNIPER_EMBEDDING_API_KEY:-${OPENROUTER_API_KEY:-}}"
export CONTEXTSNIPER_EMBEDDING_PROBE_REQUIRED="${CONTEXTSNIPER_EMBEDDING_PROBE_REQUIRED:-0}"

export CONTEXTSNIPER_RETRIEVAL_SEMANTIC_ENABLED="${CONTEXTSNIPER_RETRIEVAL_SEMANTIC_ENABLED:-1}"
export CONTEXTSNIPER_RETRIEVAL_GRAPH_ENABLED="${CONTEXTSNIPER_RETRIEVAL_GRAPH_ENABLED:-1}"
export CONTEXTSNIPER_RETRIEVAL_SYMBOLIC_ENABLED="${CONTEXTSNIPER_RETRIEVAL_SYMBOLIC_ENABLED:-1}"
export CONTEXTSNIPER_RETRIEVAL_FREQUENCY_ENABLED="${CONTEXTSNIPER_RETRIEVAL_FREQUENCY_ENABLED:-1}"

export CONTEXTSNIPER_CODE_SEARCH_CANDIDATE_MAX_FILES="${CONTEXTSNIPER_CODE_SEARCH_CANDIDATE_MAX_FILES:-80}"
export CONTEXTSNIPER_CODE_SEARCH_EMBED_MAX_FILES="${CONTEXTSNIPER_CODE_SEARCH_EMBED_MAX_FILES:-80}"
export CONTEXTSNIPER_CODE_SEARCH_MAX_SNIPPETS="${CONTEXTSNIPER_CODE_SEARCH_MAX_SNIPPETS:-500}"
export CONTEXTSNIPER_CODE_SEARCH_INGEST_CANDIDATES="${CONTEXTSNIPER_CODE_SEARCH_INGEST_CANDIDATES:-1}"
export CONTEXTSNIPER_CODE_SEARCH_INGEST_ASYNC="${CONTEXTSNIPER_CODE_SEARCH_INGEST_ASYNC:-1}"
export CONTEXTSNIPER_CODE_SEARCH_INGEST_MAX_FILES="${CONTEXTSNIPER_CODE_SEARCH_INGEST_MAX_FILES:-3}"
export CONTEXTSNIPER_CODE_SEARCH_INGEST_MAX_CHUNKS="${CONTEXTSNIPER_CODE_SEARCH_INGEST_MAX_CHUNKS:-40}"
export CONTEXTSNIPER_CODE_SEARCH_INGEST_WORKERS="${CONTEXTSNIPER_CODE_SEARCH_INGEST_WORKERS:-2}"

export CONTEXTSNIPER_CODE_FUSE_MODE="${CONTEXTSNIPER_CODE_FUSE_MODE:-weighted_rrf}"
export CONTEXTSNIPER_CODE_FUSE_W_EMBED="${CONTEXTSNIPER_CODE_FUSE_W_EMBED:-0.33}"
export CONTEXTSNIPER_CODE_FUSE_W_BM25="${CONTEXTSNIPER_CODE_FUSE_W_BM25:-0.17}"
export CONTEXTSNIPER_CODE_FUSE_W_CTAGS="${CONTEXTSNIPER_CODE_FUSE_W_CTAGS:-0.17}"
export CONTEXTSNIPER_CODE_FUSE_W_GRAPH="${CONTEXTSNIPER_CODE_FUSE_W_GRAPH:-0.33}"

export CONTEXTSNIPER_BOOTSTRAP_MAX_FILES="${CONTEXTSNIPER_BOOTSTRAP_MAX_FILES:-40}"
export CONTEXTSNIPER_BOOTSTRAP_FULL_INDEX_CAP_FILES="${CONTEXTSNIPER_BOOTSTRAP_FULL_INDEX_CAP_FILES:-40}"
export CONTEXTSNIPER_DISABLE_AFTER_TURN_EXTRACTION="${CONTEXTSNIPER_DISABLE_AFTER_TURN_EXTRACTION:-1}"
export CONTEXTSNIPER_START_LOCAL_EMBED_SERVER="${CONTEXTSNIPER_START_LOCAL_EMBED_SERVER:-0}"
export CONTEXTSNIPER_PLUGIN_AUTO_START="${CONTEXTSNIPER_PLUGIN_AUTO_START:-1}"
export CONTEXTSNIPER_PLUGIN_AUTO_STOP="${CONTEXTSNIPER_PLUGIN_AUTO_STOP:-1}"
export CONTEXTSNIPER_PLUGIN_START_WAIT="${CONTEXTSNIPER_PLUGIN_START_WAIT:-60}"
export CONTEXTSNIPER_SWE_COPY_AGFS_RUNTIME="${CONTEXTSNIPER_SWE_COPY_AGFS_RUNTIME:-1}"
export CONTEXTSNIPER_INJECT_CODE_POLICY_ON_SUBMIT="${CONTEXTSNIPER_INJECT_CODE_POLICY_ON_SUBMIT:-0}"
export CONTEXTSNIPER_APPEND_CODE_POLICY_TO_TASK="${CONTEXTSNIPER_APPEND_CODE_POLICY_TO_TASK:-1}"
export CONTEXTSNIPER_FORCE_EMBED_DIM_ALIGN="${CONTEXTSNIPER_FORCE_EMBED_DIM_ALIGN:-1}"

# Plain ContextSniper exercises code search/edit only. Native output filtering is
# reserved for the separate ContextSniper-FILTER baseline.
export CONTEXTSNIPER_FILTER_ENABLED=0
export CONTEXTSNIPER_FILTER_NATIVE_READ=0
export CONTEXTSNIPER_FILTER_NATIVE_BASH=0
export CONTEXTSNIPER_INJECT_FILTERING_PROMPT=0

if [ -n "${CONTEXTSNIPER_DIR:-}" ] && [ -z "${AGFS_BIN:-}" ] && [ -x "$CONTEXTSNIPER_DIR/agfs/build/agfs-server" ]; then
  export AGFS_BIN="$CONTEXTSNIPER_DIR/agfs/build/agfs-server"
fi

if [ "$CONTEXTSNIPER_FORCE_EMBED_DIM_ALIGN" = "1" ]; then
  _contextsniper_embedding_model="$(printf '%s' "${CONTEXTSNIPER_EMBEDDING_MODEL:-}" | tr '[:upper:]' '[:lower:]')"
  case "$_contextsniper_embedding_model" in
    *text-embedding-3-large*) export OPENGAUSS_DIMENSION=3072 ;;
    *text-embedding-3-small*|*text-embedding-ada-002*) export OPENGAUSS_DIMENSION=1536 ;;
    *) export OPENGAUSS_DIMENSION=384 ;;
  esac
  unset _contextsniper_embedding_model
fi
