#!/usr/bin/env bash
# Source this file to load safe defaults for SWE Pro runners.
# This file intentionally does NOT set secrets or provider base URLs.
#
# Usage:
#   source scripts/SWE-pro/openclaw/ContextSniper/setup_swe_env.sh
#
# IMPORTANT: When invoking OpenClaw manually after sourcing this file, cd to the
# generated SWE workspace first. Starting OpenClaw from the ContextSniper repo root makes
# native read/exec tools resolve paths against the wrong project.

# Runner defaults
export OPENCLAW_MODEL="${OPENCLAW_MODEL:-deepseek/deepseek-v4-flash}"
export SWE_PRO_INSTANCE_ID="${SWE_PRO_INSTANCE_ID:-instance_qutebrowser__qutebrowser-f91ace96223cac8161c16dd061907e138fe85111-v059c6fdc75567943479b23ebca7c07b5e9a7f34c}"
export CONTEXTSNIPER_CACHE_HOME="${CONTEXTSNIPER_CACHE_HOME:-${XDG_CACHE_HOME:-$HOME/.cache}/contextsniper}"
export REPO_BASE="${REPO_BASE:-$CONTEXTSNIPER_CACHE_HOME/swe-pro/openclaw/contextsniper/cache/repo}"
export SWE_OUTPUT_ROOT="${SWE_OUTPUT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/output_logs}"

# ContextSniper mode local service defaults
export CONTEXTSNIPER_HTTP_PORT="${CONTEXTSNIPER_HTTP_PORT:-8090}"
export CONTEXTSNIPER_URL="${CONTEXTSNIPER_URL:-http://127.0.0.1:${CONTEXTSNIPER_HTTP_PORT}}"
export AGFS_BASE_URL="${AGFS_BASE_URL:-http://127.0.0.1:1833}"
export VECTOR_DB_TYPE="${VECTOR_DB_TYPE:-memory}"
export CONTEXTSNIPER_CODE_TOGGLE_FORCE="${CONTEXTSNIPER_CODE_TOGGLE_FORCE:-true}"

# Identity defaults for MCP calls
export CONTEXTSNIPER_ACCOUNT_ID="${CONTEXTSNIPER_ACCOUNT_ID:-acct-demo}"
export CONTEXTSNIPER_USER_ID="${CONTEXTSNIPER_USER_ID:-u-openclaw}"
export CONTEXTSNIPER_AGENT_ID="${CONTEXTSNIPER_AGENT_ID:-openclaw-swe}"

# Embedding behavior defaults (no secrets/no base URL values here)
export EMBEDDING_PROVIDER="${EMBEDDING_PROVIDER:-openai}"
export CONTEXTSNIPER_EMBEDDING_API_KEY="${CONTEXTSNIPER_EMBEDDING_API_KEY:-${RTC_EMBEDDING_API_KEY:-}}"
export CONTEXTSNIPER_EMBEDDING_BASE_URL="${CONTEXTSNIPER_EMBEDDING_BASE_URL:-${RTC_EMBEDDING_BASE_URL:-}}"
export CONTEXTSNIPER_EMBEDDING_MODEL="${CONTEXTSNIPER_EMBEDDING_MODEL:-${RTC_EMBEDDING_MODEL:-}}"
export CONTEXTSNIPER_EMBEDDING_MODEL="${CONTEXTSNIPER_EMBEDDING_MODEL:-text-embedding-3-small}"

# Indexing/search tuning defaults
export CONTEXTSNIPER_CODE_SEARCH_CANDIDATE_MAX_FILES="${CONTEXTSNIPER_CODE_SEARCH_CANDIDATE_MAX_FILES:-40}"
export CONTEXTSNIPER_CODE_SEARCH_EMBED_MAX_FILES="${CONTEXTSNIPER_CODE_SEARCH_EMBED_MAX_FILES:-8}"
export CONTEXTSNIPER_CODE_SEARCH_MAX_SNIPPETS="${CONTEXTSNIPER_CODE_SEARCH_MAX_SNIPPETS:-120}"
export CONTEXTSNIPER_CODE_SEARCH_INGEST_CANDIDATES="${CONTEXTSNIPER_CODE_SEARCH_INGEST_CANDIDATES:-1}"
export CONTEXTSNIPER_CODE_SEARCH_INGEST_ASYNC="${CONTEXTSNIPER_CODE_SEARCH_INGEST_ASYNC:-1}"
export CONTEXTSNIPER_CODE_SEARCH_INGEST_MAX_FILES="${CONTEXTSNIPER_CODE_SEARCH_INGEST_MAX_FILES:-3}"
export CONTEXTSNIPER_CODE_SEARCH_INGEST_MAX_CHUNKS="${CONTEXTSNIPER_CODE_SEARCH_INGEST_MAX_CHUNKS:-40}"
export CONTEXTSNIPER_CODE_SEARCH_INGEST_WORKERS="${CONTEXTSNIPER_CODE_SEARCH_INGEST_WORKERS:-2}"
export CONTEXTSNIPER_CODE_FUSE_MODE="${CONTEXTSNIPER_CODE_FUSE_MODE:-weighted_rrf}"
export CONTEXTSNIPER_CODE_FUSE_W_EMBED="${CONTEXTSNIPER_CODE_FUSE_W_EMBED:-0.33}"
export CONTEXTSNIPER_CODE_FUSE_W_BM25="${CONTEXTSNIPER_CODE_FUSE_W_BM25:-0.17}"
export CONTEXTSNIPER_CODE_FUSE_W_CTAGS="${CONTEXTSNIPER_CODE_FUSE_W_CTAGS:-0.17}"
export CONTEXTSNIPER_CODE_FUSE_W_GRAPH="${CONTEXTSNIPER_CODE_FUSE_W_GRAPH:-0.33}"
export CONTEXTSNIPER_SEARCH_LIMIT="${CONTEXTSNIPER_SEARCH_LIMIT:-5}"
export CONTEXTSNIPER_BOOTSTRAP_MAX_FILES="${CONTEXTSNIPER_BOOTSTRAP_MAX_FILES:-40}"
export CONTEXTSNIPER_BOOTSTRAP_FULL_INDEX_CAP_FILES="${CONTEXTSNIPER_BOOTSTRAP_FULL_INDEX_CAP_FILES:-40}"
export CONTEXTSNIPER_START_LOCAL_EMBED_SERVER="${CONTEXTSNIPER_START_LOCAL_EMBED_SERVER:-0}"
export SWE_VALIDATION_FORCE_LOCAL="${SWE_VALIDATION_FORCE_LOCAL:-1}"
export SWE_SKIP_VALIDATION="${SWE_SKIP_VALIDATION:-1}"

# Plain OpenClaw ContextSniper mode should exercise search/edit only. Read/exec output
# filtering belongs to scripts/SWE-pro/openclaw/ContextSniper-FILTER.
export CONTEXTSNIPER_INJECT_FILTERING_PROMPT=0
export CONTEXTSNIPER_FILTER_ENABLED=0
export CONTEXTSNIPER_FILTER_NATIVE_READ=0
export CONTEXTSNIPER_FILTER_NATIVE_BASH=0

echo "Loaded scripts/SWE-pro/openclaw SWE defaults."
echo "SWE_PRO_INSTANCE_ID=$SWE_PRO_INSTANCE_ID"
echo "OPENCLAW_MODEL=$OPENCLAW_MODEL"
echo "CONTEXTSNIPER_URL=$CONTEXTSNIPER_URL"
echo "EMBEDDING_PROVIDER=$EMBEDDING_PROVIDER"
echo "CONTEXTSNIPER_SEARCH_LIMIT=$CONTEXTSNIPER_SEARCH_LIMIT"
echo "SWE_SKIP_VALIDATION=$SWE_SKIP_VALIDATION"
if [ -n "${CONTEXTSNIPER_EMBEDDING_API_KEY:-}" ]; then
  echo "CONTEXTSNIPER_EMBEDDING_API_KEY=set"
else
  echo "CONTEXTSNIPER_EMBEDDING_API_KEY=<empty> (set this before ContextSniper run)"
fi
